[colors.primary]
background = '#121410'
foreground = '#e3e3dc'
 
[colors.cursor]
text = '#e3e3dc'
cursor = '#c4c8bb' 
 
[colors.vi_mode_cursor]
text = '#121410'
cursor = '#b2d096' 
 
[colors.search.matches]
foreground = '#44483e' 
background = '#93d3c2' 
 
[colors.search.focused_match]
foreground = '#44483e' 
background = '#b2d096' 
 
[colors.footer_bar]
foreground = '#44483e' 
background = '#e3e3dc' 
 
[colors.hints.start]
foreground = '#44483e' 
background = '#bfcbaf' 
 
[colors.hints.end]
foreground = '#44483e' 
background = '#bfcbaf' 
 
[colors.selection]
text = '#121410'
background = '#b2d096'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#b2d096' 
yellow = '#4c6636' 
blue = '#b2d096' 
magenta = '#93d3c2' 
cyan = '#bfcbaf' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 